package view.panels;

import Model.ModelCellProveedores;
import Model.conexion.CrudMysql;
import controller.JsonProveedoresCRUD;
import controller.JsonUserValidation;
import controller.ValidateRegular;
import controller.viewExcel.Modelo_Excel;
import java.awt.BorderLayout;
import java.io.File;
import static java.lang.String.valueOf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import table.TableProveedores.TableActionEventProveedores;
import view.panels.forms.FormProveedores;
import view.panels.forms.Maximize;

public class PanelProveedores extends javax.swing.JPanel {

    private static List<ModelCellProveedores> listProveedor;
    private ArrayList<String> busquedaLista = new ArrayList<>();
    private static String searchSelect = "";
    private String banderaSearch = "nombres";

    public PanelProveedores() {
        initComponents();
        TableProveedores.fixTable(jScrollPane2);
        TableProveedores.setIconsColumns(9, 6, 7);
        listarProveedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        ContentPanel = new javax.swing.JPanel();
        ContentButtonsSearch = new javax.swing.JPanel();
        TitleProveedores = new javax.swing.JLabel();
        btn_ExportarExcel = new javax.swing.JLabel();
        btn_AgregarProveedores = new javax.swing.JLabel();
        ContextSearch = new javax.swing.JPanel();
        TextSearch = new javax.swing.JPanel();
        txtSearchProveedor = new javax.swing.JTextField();
        IconSearch = new javax.swing.JLabel();
        typeName = new javax.swing.JLabel();
        typeRuc = new javax.swing.JLabel();
        typeTelefono = new javax.swing.JLabel();
        typeProducto = new javax.swing.JLabel();
        JcomboTipo = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        ContentTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableProveedores = new table.TableProveedores.TableProveedores();

        ContentButtonsSearch.setBackground(new java.awt.Color(250, 250, 250));

        TitleProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Proveedores.png"))); // NOI18N

        btn_ExportarExcel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ExportarExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_ExportarExcel.png"))); // NOI18N
        btn_ExportarExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ExportarExcelMouseClicked(evt);
            }
        });

        btn_AgregarProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_NewProveedor.png"))); // NOI18N
        btn_AgregarProveedores.setToolTipText("");
        btn_AgregarProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AgregarProveedoresMouseClicked(evt);
            }
        });

        ContextSearch.setBackground(new java.awt.Color(250, 250, 250));

        TextSearch.setBackground(new java.awt.Color(255, 255, 255));
        TextSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtSearchProveedor.setBackground(new java.awt.Color(255, 255, 255));
        txtSearchProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        txtSearchProveedor.setForeground(new java.awt.Color(16, 21, 64));
        txtSearchProveedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSearchProveedor.setText(" ");
        txtSearchProveedor.setBorder(null);
        txtSearchProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchProveedorKeyReleased(evt);
            }
        });

        IconSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N

        javax.swing.GroupLayout TextSearchLayout = new javax.swing.GroupLayout(TextSearch);
        TextSearch.setLayout(TextSearchLayout);
        TextSearchLayout.setHorizontalGroup(
            TextSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextSearchLayout.createSequentialGroup()
                .addComponent(IconSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSearchProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
        );
        TextSearchLayout.setVerticalGroup(
            TextSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextSearchLayout.createSequentialGroup()
                .addGroup(TextSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(IconSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(txtSearchProveedor))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        typeName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/types/typeNombre.png"))); // NOI18N
        typeName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typeNameMouseClicked(evt);
            }
        });

        typeRuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/types/typeRuc.png"))); // NOI18N
        typeRuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typeRucMouseClicked(evt);
            }
        });

        typeTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/types/typeTelefono.png"))); // NOI18N
        typeTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typeTelefonoMouseClicked(evt);
            }
        });

        typeProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/types/typeProductos.png"))); // NOI18N
        typeProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typeProductoMouseClicked(evt);
            }
        });

        JcomboTipo.setBackground(new java.awt.Color(255, 255, 255));
        JcomboTipo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 17)); // NOI18N
        JcomboTipo.setForeground(new java.awt.Color(16, 21, 64));
        JcomboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Juridica", "Natural" }));
        JcomboTipo.setBorder(null);
        JcomboTipo.setFocusable(false);
        JcomboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContextSearchLayout = new javax.swing.GroupLayout(ContextSearch);
        ContextSearch.setLayout(ContextSearchLayout);
        ContextSearchLayout.setHorizontalGroup(
            ContextSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContextSearchLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(typeName)
                .addGap(18, 18, 18)
                .addComponent(typeRuc)
                .addGap(18, 18, 18)
                .addComponent(typeTelefono)
                .addGap(18, 18, 18)
                .addComponent(typeProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JcomboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        ContextSearchLayout.setVerticalGroup(
            ContextSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContextSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContextSearchLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(ContextSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcomboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeName)
                    .addComponent(typeRuc)
                    .addComponent(typeTelefono)
                    .addComponent(typeProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(250, 250, 250));
        jSeparator1.setForeground(new java.awt.Color(224, 225, 234));

        jSeparator4.setBackground(new java.awt.Color(250, 250, 250));
        jSeparator4.setForeground(new java.awt.Color(224, 225, 234));

        javax.swing.GroupLayout ContentButtonsSearchLayout = new javax.swing.GroupLayout(ContentButtonsSearch);
        ContentButtonsSearch.setLayout(ContentButtonsSearchLayout);
        ContentButtonsSearchLayout.setHorizontalGroup(
            ContentButtonsSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContextSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContentButtonsSearchLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ContentButtonsSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentButtonsSearchLayout.createSequentialGroup()
                        .addComponent(TitleProveedores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ExportarExcel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_AgregarProveedores)
                        .addGap(44, 44, 44))
                    .addGroup(ContentButtonsSearchLayout.createSequentialGroup()
                        .addGroup(ContentButtonsSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentButtonsSearchLayout.createSequentialGroup()
                                .addComponent(jSeparator1)
                                .addGap(3, 3, 3))
                            .addComponent(jSeparator4))
                        .addGap(34, 34, 34))))
        );
        ContentButtonsSearchLayout.setVerticalGroup(
            ContentButtonsSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentButtonsSearchLayout.createSequentialGroup()
                .addGroup(ContentButtonsSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentButtonsSearchLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(TitleProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentButtonsSearchLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(ContentButtonsSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ExportarExcel)
                            .addComponent(btn_AgregarProveedores))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContextSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ContentTable.setBackground(new java.awt.Color(255, 255, 255));

        TableProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TableProveedores);

        javax.swing.GroupLayout ContentTableLayout = new javax.swing.GroupLayout(ContentTable);
        ContentTable.setLayout(ContentTableLayout);
        ContentTableLayout.setHorizontalGroup(
            ContentTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentTableLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2)
                .addGap(62, 62, 62))
        );
        ContentTableLayout.setVerticalGroup(
            ContentTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentButtonsSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContentTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addComponent(ContentButtonsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ContentTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarProveedoresMouseClicked
        //JsonProveedoreCRUD.addProveedore(ModelCellProveedores);
        addContainer(new FormProveedores(), getWidth(), getHeight(), ContentPanel);
    }//GEN-LAST:event_btn_AgregarProveedoresMouseClicked

    private void txtSearchProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchProveedorKeyReleased
        System.out.println("Campturadbno el texto: " + txtSearchProveedor.getText());
        if (txtSearchProveedor.getText().trim().isEmpty()) {
            listarProveedores();
        } else {
            switch (banderaSearch) {
                case "nombres":
                    listarNombres();
                    break;
                case "productos":
                    listarProductos();
                    break;
                case "telefono":
                    listarTelefono();
                    break;
                case "ruc":
                    listarNumero();
                    break;
                case "tipo":
                    listarNumero();
                    break;
                default:
                    System.out.println("Error");
            }
        }
    }//GEN-LAST:event_txtSearchProveedorKeyReleased

    private void typeNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeNameMouseClicked
        banderaSearch = "nombres";
        listarNombres();
    }//GEN-LAST:event_typeNameMouseClicked

    private void JcomboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboTipoActionPerformed
        System.out.println("Elemento seleccionado: " + JcomboTipo.getSelectedItem());
        banderaSearch = "tipo";
        listarTipo();
    }//GEN-LAST:event_JcomboTipoActionPerformed

    private void typeTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeTelefonoMouseClicked
        banderaSearch = "telefono";
        listarTelefono();
    }//GEN-LAST:event_typeTelefonoMouseClicked

    private void typeProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeProductoMouseClicked
        banderaSearch = "productos";
        listarProductos();
    }//GEN-LAST:event_typeProductoMouseClicked

    private void typeRucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeRucMouseClicked
        banderaSearch = "ruc";
        listarNumero();
    }//GEN-LAST:event_typeRucMouseClicked

    private void btn_ExportarExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ExportarExcelMouseClicked
         JFileChooser archivo_selec = new JFileChooser();
        File archivo;
        Modelo_Excel model_ex = new Modelo_Excel();
        
        if (archivo_selec.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
            archivo = archivo_selec.getSelectedFile();
            
            String nombreArchivo = archivo.getName();
            if (!nombreArchivo.toLowerCase().endsWith(".xls") && !nombreArchivo.toLowerCase().endsWith(".xlsx")) {
                // Agregar extensión .xlsx si no está presente en el nombre del archivo
                nombreArchivo += ".xlsx";
                archivo = new File(archivo.getParentFile(), nombreArchivo);
            }

            // Continuar con el código para guardar el archivo
            if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
                model_ex.exportacion(archivo, TableProveedores, 6);
                /*MENSAJE DE EXITO*/
                ImageIcon icononew = new ImageIcon(JsonUserValidation.class.getResource("/img/message/comprobado.png"));
                JOptionPane.showMessageDialog(null, "Archivo creado", "", 0, icononew);
            } else {
                JOptionPane.showMessageDialog(null, "Elija un formato válido");
            }
        }
    }//GEN-LAST:event_btn_ExportarExcelMouseClicked

    /*EVENTO DE BOTONES*/
    TableActionEventProveedores event = new TableActionEventProveedores() {

        @Override
        public void onEdit(ModelCellProveedores proveedores) {
            Maximize.updateCrud = true;
            ModelCellProveedores updateProveedor = listProveedor.get(TableProveedores.getSelectedRow());
            ValidateRegular.updateProveedor = updateProveedor;
            FormProveedores fCl = new FormProveedores();
            addContainer(fCl, getWidth(), getHeight(), ContentPanel);
        }

        @Override
        public void onDelete(ModelCellProveedores proveedores) {
            System.out.println("DELETE PROVEEDORES");
            ModelCellProveedores deleteProveedores = listProveedor.get(TableProveedores.getSelectedRow());
            String[] opciones = {"Si", "No"};
            ImageIcon icono = new ImageIcon(getClass().getResource("/img/message/advertencia.png")); // Ruta al archivo de imagen del ícono
            int opcion = JOptionPane.showOptionDialog(null, "¿Desea eliminar al proveedor " + deleteProveedores.getNombres() + " ?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icono, opciones, opciones[0]);
            if (opcion == JOptionPane.YES_OPTION) {
                JsonProveedoresCRUD.deleteProveedor(deleteProveedores.getIdProveedor());
                if (ValidateRegular.conexion) {
                    try {
                        CrudMysql.crudMysqlProveedores();
                    } catch (Exception e) {
                        System.out.println("Sin conexion a internet proveedor no eliminado en base de datos");
                    }
                }
            }
            listarProveedores();
        }
    };

    /*INIT DATA*/
    private void listarProveedores() {
        listProveedor = JsonProveedoresCRUD.returnProveedores();
        DefaultTableModel modelo = new DefaultTableModel();
        String columns[] = {"RUC", "Nombres", "Tipo", "Productos", "Telefono", "Correo", "Editar", "Eliminar"};
        TableProveedores.setModel(modelo);
        modelo.setColumnIdentifiers(columns);
        if (listProveedor != null) {
            for (ModelCellProveedores cl : listProveedor) {
                //TableProveedores.addRow(new ModelCellProduct("13123sd", "galleta soda V",
                TableProveedores.addRow(new ModelCellProveedores(cl.getRuc(), cl.getNombres(), cl.getTipo(), cl.getProductos(), cl.getTelefono(),
                        cl.getCorreo()).toRowTable(event));
            }
        }
    }

    private void listarProveedorType(List<ModelCellProveedores> typeProveedoreses) {
        DefaultTableModel modelo = new DefaultTableModel();
        String columns[] = {"RUC", "Nombres", "Tipo", "Productos", "Telefono", "Correo", "Editar", "Eliminar"};
        TableProveedores.setModel(modelo);
        modelo.setColumnIdentifiers(columns);
        for (int i = 0; i < typeProveedoreses.size(); i++) {
            TableProveedores.addRow(new ModelCellProveedores(typeProveedoreses.get(i).getRuc(), typeProveedoreses.get(i).getNombres(), typeProveedoreses.get(i).getTipo(), typeProveedoreses.get(i).getProductos(), typeProveedoreses.get(i).getTelefono(),
                    typeProveedoreses.get(i).getCorreo()).toRowTable(event));
        }
    }

    private void listarNombres() {
        List<ModelCellProveedores> newCellProveedore = new JsonProveedoresCRUD().searchListProveedorNombre(txtSearchProveedor.getText());
        listarProveedorType(newCellProveedore);
    }

    private void listarProductos() {
        List<ModelCellProveedores> newCellProveedore = new JsonProveedoresCRUD().searchListProveedorProductos(txtSearchProveedor.getText());
        listarProveedorType(newCellProveedore);
    }

    private void listarTelefono() {
        List<ModelCellProveedores> newCellProveedore = new JsonProveedoresCRUD().searchListProveedorTelefono(txtSearchProveedor.getText());
        listarProveedorType(newCellProveedore);
    }

    private void listarNumero() {
        List<ModelCellProveedores> newCellProveedore = new JsonProveedoresCRUD().searchListProveedorNumero(txtSearchProveedor.getText());
        listarProveedorType(newCellProveedore);
    }

    private void listarTipo() {
        List<ModelCellProveedores> newCellProveedore = new JsonProveedoresCRUD().searchListProveedorTipoProveedor(valueOf(JcomboTipo.getSelectedItem()));
        listarProveedorType(newCellProveedore);
    }

    /**
     *
     * @param p Panel de Ingreso
     * @param width Ancho
     * @param height Alto
     * @param c contenedor
     */
    public void addContainer(JPanel p, int width, int height, JPanel c) {
        p.setSize(width, height);
        p.setLocation(0, 0);
        c.removeAll();
        c.add(p, BorderLayout.CENTER);
        c.revalidate();
        c.repaint();
    }

    public void llenadoBusqueda() {
        busquedaLista.add("nombre");
        busquedaLista.add("ruc");
        busquedaLista.add("telefono");
        busquedaLista.add("productos");
        busquedaLista.add("tipo");
        busquedaLista.add("ultimo");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentButtonsSearch;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel ContentTable;
    private javax.swing.JPanel ContextSearch;
    private javax.swing.JLabel IconSearch;
    private javax.swing.JComboBox<String> JcomboTipo;
    private table.TableProveedores.TableProveedores TableProveedores;
    private javax.swing.JPanel TextSearch;
    private javax.swing.JLabel TitleProveedores;
    private javax.swing.JLabel btn_AgregarProveedores;
    private javax.swing.JLabel btn_ExportarExcel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtSearchProveedor;
    private javax.swing.JLabel typeName;
    private javax.swing.JLabel typeProducto;
    private javax.swing.JLabel typeRuc;
    private javax.swing.JLabel typeTelefono;
    // End of variables declaration//GEN-END:variables

}
